# DAL database file
sqlite_db = /home/system/datapanel/sqlite/httpd_p1.db

# The apache server unique id
server_id=1

# This is where the backup log files will be created
log_root=/home/system/apache-logs

# Sets the log type the parser is reading
log_type=custm

# If the parser is unable to find the domain or the log line was not parseable, then it will be written here
apache_logfile=/var/log/httpd.p1/access_log

# User log files will have this permission when created
userlog_perm=0444

# DAL logfile
logfile=/var/log/httpd.p1/dal_access.log

# Performance setting - describes how many requests will be committed at once
commit_count = 200

# If DAL fails to insert data for commit_hard_limit requests then it will drop the data (to avoid memory leak)
# MUST BE GREATER THAN commit_count
commit_hard_limit = 300

# All apache requests will also be logged here - this is truncated every day at midnight
global_logfile=/var/log/httpd.p1/access_global_log
